sudo: required

services:
  - docker

before_install:
  - docker pull tonyhb/flow:0.37.4
  - docker pull tonyhb/node-yarn:7.2-slim

script:
  - make ci

after_success:
  - bash <(curl -s https://codecov.io/bash)
